apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
  labels:
    app: node-app-todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app-todo
  template:
    metadata:
      labels:
        app: node-app-todo
    spec:
      containers:
      - name: node-app-todo
        image:node-app-todo:latest
        ports:
        - containerPort: 3000
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: node-app-todo
spec:
  selector:
    app: node-app-todo
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31110
