apiVersion: v1
kind: Pod
metadata:
  name: node-pod
  namespace: node-app

spec:
  containers:
    - name: node-container
      image: sakshiipatill/node-app-todo-1
      ports:
        - containerPort: 8000
